// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcu-6V0FkbnH7lcozcHiHMQwCALgsS-aA',
    appId: '1:1030684162200:web:857a4b117b31b602e478ed',
    messagingSenderId: '1030684162200',
    projectId: 'buslanka-ca425',
    authDomain: 'buslanka-ca425.firebaseapp.com',
    databaseURL: 'https://buslanka-ca425-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buslanka-ca425.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvp_Bg0WFBVqbHMu5AWmNg9hreyzfu7xA',
    appId: '1:1030684162200:android:7d732a81de8d3b73e478ed',
    messagingSenderId: '1030684162200',
    projectId: 'buslanka-ca425',
    databaseURL: 'https://buslanka-ca425-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buslanka-ca425.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhpVjVMFn-2bkG_Mw0oJdQSBy9gpqjNnk',
    appId: '1:1030684162200:ios:2442466331d51d39e478ed',
    messagingSenderId: '1030684162200',
    projectId: 'buslanka-ca425',
    databaseURL: 'https://buslanka-ca425-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buslanka-ca425.firebasestorage.app',
    iosBundleId: 'com.example.buslanka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhpVjVMFn-2bkG_Mw0oJdQSBy9gpqjNnk',
    appId: '1:1030684162200:ios:2442466331d51d39e478ed',
    messagingSenderId: '1030684162200',
    projectId: 'buslanka-ca425',
    databaseURL: 'https://buslanka-ca425-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buslanka-ca425.firebasestorage.app',
    iosBundleId: 'com.example.buslanka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcu-6V0FkbnH7lcozcHiHMQwCALgsS-aA',
    appId: '1:1030684162200:web:7907b7c0f31934e0e478ed',
    messagingSenderId: '1030684162200',
    projectId: 'buslanka-ca425',
    authDomain: 'buslanka-ca425.firebaseapp.com',
    databaseURL: 'https://buslanka-ca425-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buslanka-ca425.firebasestorage.app',
  );
}
